networks:
  network-zabbix:
    driver: bridge

services:
  postgres:
    container_name: zabbix-postgres
    image: postgres:17-alpine
    networks:
      - network-zabbix
    volumes:
      - './zabbix/pgsql:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ${ZABBIX_DB_PASSWORD:-zabbixfg}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zabbix -d zabbix"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    networks:
      - network-zabbix
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - './zabbix/clickhouse:/var/lib/clickhouse'
    environment:
      CLICKHOUSE_DB: zabbix
      CLICKHOUSE_USER: zabbix
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-clickhousefg}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    restart: always

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:latest
    networks:
      - network-zabbix
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ${ZABBIX_DB_PASSWORD:-zabbixfg}
    depends_on:
      postgres:
        condition: service_healthy

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-pgsql:latest
    networks:
      - network-zabbix
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ${ZABBIX_DB_PASSWORD:-zabbixfg}
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_NAME: Zabbix
      PHP_TZ: America/Sao_Paulo
    depends_on:
      postgres:
        condition: service_healthy
      zabbix-server:
        condition: service_started

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - network-zabbix
    restart: always
    ports:
      - '3000:3000'
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
    depends_on:
      zabbix-server:
        condition: service_started

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:latest
    user: root
    networks:
      - network-zabbix
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      ZBX_HOSTNAME: Zabbix server
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      zabbix-server:
        condition: service_started