version: '3.1'

networks:
  network-zabbix:
    driver: bridge

services:
  traefik:
    image: traefik:v2.5.5
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker
    networks:
      - "network-zabbix"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.http.routers.traefik.rule: Host(`dash.localhost`)
      traefik.http.routers.traefik.service: api@internal
    ports:
      - "80:80"

  zabbix-pg-db:
    container_name: zabbix-pg-db
    image: timescale/timescaledb:latest-pg13
    command: postgres -c 'max_connections=200'
    networks:
      - network-zabbix
    ports:
      - '5432:5432'
    volumes:
      - './zabbix/pgsql:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbixfg
      - POSTGRES_DB=zabbix

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:ubuntu-trunk
    networks:
      - network-zabbix
    links:
      - zabbix-pg-db
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - ZBX_NODEADDRESS=zabbix-server
      - DB_SERVER_HOST=zabbix-pg-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbixfg
      - POSTGRES_DB=zabbix
      - ENABLE_TIMESCALEDB=true
      - ZBX_HANODENAME=zabbix1
    depends_on:
      - zabbix-pg-db

  zabbix-server02:
    container_name: zabbix-server02
    image: zabbix/zabbix-server-pgsql:ubuntu-trunk
    networks:
      - network-zabbix
    links:
      - zabbix-pg-db
    restart: always
    ports:
      - '10052:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - ZBX_NODEADDRESS=zabbix-server02
      - DB_SERVER_HOST=zabbix-pg-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbixfg
      - POSTGRES_DB=zabbix
      - ENABLE_TIMESCALEDB=true
      - ZBX_HANODENAME=zabbix2

    depends_on:
      - zabbix-pg-db

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-trunk
    networks:
      - network-zabbix
    links:
      - zabbix-pg-db
    restart: always
    environment:
      - DB_SERVER_HOST=zabbix-pg-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbixfg
      - POSTGRES_DB=zabbix
      - PHP_TZ=America/Sao_Paulo
      - ZBX_SERVER_NAME=ZBX Stack
    labels: # auto-detect port 80 in next line
      traefik.http.routers.zabbix.rule: Host(`zabbix.localhost`)
    depends_on:
      - zabbix-pg-db
   
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    links:
      - zabbix-pg-db
      - zabbix-server
    restart: always
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
        - "traefik.http.routers.grafana.entrypoints=web"    
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    depends_on:
      - zabbix-pg-db
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-trunk
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
      - zabbix-server02
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-server,zabbix-server02
